apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: satellite
  template:
    metadata:
      labels:
        app: satellite
    spec:
      containers:
        - name: satellite
          image: busybox
          command:
            - sh
            - -c
            - |
              while true; do
                echo "📡 Satellite pinging ground-control..."
                wget -qO- http://ground-control || echo "failed"
                sleep 5
              done
