apiVersion: v1
kind: Service
metadata:
  name: satellite-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: satellite-0
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: satellite-1
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: satellite-1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: satellite-2
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: satellite-2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
