apiVersion: apps/v1
kind: Deployment
metadata:
  name: ground-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ground-control
  template:
    metadata:
      labels:
        app: ground-control
    spec:
      imagePullSecrets:
      - name: harbor-regcred
      containers:
        - name: ground-control
          image: host.k3d.internal:8888/satellites/ground-control:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "gc-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "groundcontrol"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"

            - name: HARBOR_USERNAME
              value: "admin"
            - name: HARBOR_PASSWORD
              value: "Harbor12345"
            - name: HARBOR_URL
              value: "http://host.k3d.internal:8888"

            - name: PORT
              value: "8000"

            - name: ADMIN_PASSWORD
              value: "Password@1"

            - name: SKIP_HARBOR_HEALTH_CHECK
              value: "true"

            - name: SPIFFE_ENABLED
              value: "false"
            - name: SPIFFE_TRUST_DOMAIN
              value: "harbor-satellite.local"
            - name: SPIFFE_PROVIDER
              value: "sidecar"
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///run/spire/sockets/agent.sock"
