apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-seed
  namespace: harbor
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: curlimages/curl
          command:
            - sh
            - -c
            - |
              echo "Creating project..."

              curl -s -o /dev/null -w "%{http_code}" \
                -u "admin:admin" \
                -X POST \
                "http://harbor.harbor.svc.cluster.local/api/v2.0/projects" \
                -H "Content-Type: application/json" \
                -d '{"project_name": "satellites", "public": true}'

              echo "Done"
