apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-seed-images
  namespace: harbor
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed-images
          image: gcr.io/go-containerregistry/crane:debug
          command:
            - sh
            - -c
            - |
              echo "🔐 Logging into Harbor..."

              crane auth login harbor.harbor.svc.cluster.local \
                -u admin -p admin

              echo "📦 Copying images..."

              crane copy --no-clobber --platform=linux/amd64 docker.io/library/nginx:latest harbor.harbor.svc.cluster.local/satellites/nginx:latest
              crane copy --no-clobber docker.io/library/alpine:latest harbor.harbor.svc.cluster.local/satellites/alpine:latest
              crane copy --no-clobber docker.io/library/busybox:latest harbor.harbor.svc.cluster.local/satellites/busybox:latest

              echo "✅ Done"
