apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-seed
  namespace: harbor
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: dockerhub-regcred
      containers:
        - name: seed
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              echo "Installing curl..."
              apk add --no-cache curl

              echo "Creating project..."

              curl -v \
                -u "admin:admin" \
                -X POST \
                "http://harbor.harbor.svc.cluster.local/api/v2.0/projects" \
                -H "Content-Type: application/json" \
                -d '{"project_name": "satellites", "public": true}'

              echo "Done"
